### ISSUE TITLE
make public

### ISSUE THREAD

**Issue by klinares** [Johniakaky/Testing-repository-727#1]
Johnia, 

Can you make this github public? I can't do it from my end b/c I don't have the privilege.

**Comment by Johniakaky** [comment]
Hello Kelvin,
I have seen that my GitHub is public. If there are still some issues we can
go through it together after class.

**Comment by klinares** [comment]
Thanks for checking. I can't see on my end unless you give me more privileges I think as admin

**Comment by Johniakaky** [comment]
Please let me know how to do that after class.


Johnia
